# Process Multiple Long Strips

In [1]:
#%% imports
from pathlib import Path
# import json
# import configparser
import pprint
pp = pprint.PrettyPrinter(indent=4);
import time
import math
from collections import namedtuple

# # pip install slicerio
# import slicerio.server

# # packages for 3d
# #   # for OCT 3D stuff and using in jupyter
# #   - trame-jupyter-extension
# #   - trame
# #   - trame-vtk
# #   - trame-vuetify
# #   - ipywidgets

import matplotlib.pyplot as plt
import plotly.express as px

# interactive panels
import panel as pn
pn.extension('plotly');

import numpy as np
import pandas as pd
import addict

import cv2
import skimage
import scipy.signal

import pyvista as pv
from PIL import Image
import SimpleITK as sitk

# with vedo
#from vedo import dataurl, Volume, Text2D
import vedo
vedo.settings.default_backend = 'vtk'
#from vedo.applications import Slicer3DPlotter
import naatos_oct_tools.plotters.vedo_plotters as vedo_plotters
import naatos_oct_tools.plotters.sitk_plotters as sitk_plotters

import naatos_oct_tools.thorlabs_oct_file_reading
import naatos_oct_tools.oct_linear_scan_processing

import papermill

In [2]:
# Magics to autoreload submodules when they are modified
%load_ext autoreload
%autoreload 2

In [3]:
#%% Test Record Excel
dftests = pd.read_excel(
    r'C:\Users\SimonGhionea\Global Health Labs, Inc\NAATOS Product Feasibility - TB V1 - General - Internal - Wax Valve\OCT\Test\OCT_wax_valve_test_record.xlsx',
    skiprows=1
)
dftests = dftests.iloc[:,1:]
dftests.rename(columns={'Unnamed: 19':'Notes'},inplace=True)
dftests

,Test ID,Test date,Test name,Batch,Strip,Wax (mg/mm),Fixture,"X, FOV","Y, FOV","Z, FOV",...,Right edge (mm),Left edge (mm),Strip length (mm),Speed/Sensitivity,Averaging (A-scan),Refractive Index,File size (MB),Total size (GB),ProcessingNotes,Notes
0,NaN,2025-03-26,GHL_pyapp_20250326T1258,oven aging test day 1,strip 7,NaN,"old, with tape",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2025-03-26,GHL_pyapp_20250326T1403,oven aging test day 1,strip 10,NaN,"old, with tape",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2025-03-26,GHL_pyapp_20250326T1416,oven aging test day 1,strip 14,NaN,"old, with tape",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,2025-03-27,GHL_pyapp_20250327T1428,oven aging test day 2,strip 7,NaN,"old, with 3d print clamps",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,2025-03-27,GHL_pyapp_20250327T1438,oven aging test day 2,strip 10,NaN,"old, with 3d print clamps",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,113.0,2025-06-05,GHL_pyapp_20250605T1621,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0403#4 0.392,0.392,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,114.0,2025-06-05,GHL_pyapp_20250605T1625,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0403#1BluMark 0.382,0.382,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,115.0,2025-06-05,GHL_pyapp_20250605T1628,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0403#7 0.383,0.383,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,116.0,2025-06-05,GHL_pyapp_20250605T1633,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0402#14 0.384,0.384,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,117.0,2025-06-05,GHL_pyapp_20250605T1636,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0402#26 0.398,0.398,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#%% Filter The Tests To Process
# dfmasks = [
#     (dftests['Test date']<'2025-03-28') & (dftests['Test date']>='2025-03-26'),
#     dftests['Test name'] != 'GHL_pyapp_20250326T1258'
# ]
# dfmasks = [
#     (dftests['Test date']<='2025-04-15') & (dftests['Test date']>='2025-04-14')
# ]
# dfmasks = [
#     dftests['Test date']=='2025-05-05',
# ]
dfmasks = [
    dftests['Test date']=='2025-06-05',
    #dftests['Test name']!='GHL_pyapp_20250512T',
    #dftests['ProcessingNotes'].str.startswith('loc runF'),
    #~dftests['Batch'].str.contains('Valve')
]

dffilt = dftests[np.all(dfmasks,axis=0)]
dffilt

,Test ID,Test date,Test name,Batch,Strip,Wax (mg/mm),Fixture,"X, FOV","Y, FOV","Z, FOV",...,Right edge (mm),Left edge (mm),Strip length (mm),Speed/Sensitivity,Averaging (A-scan),Refractive Index,File size (MB),Total size (GB),ProcessingNotes,Notes
74,69.0,2025-06-05,GHL_pyapp_20250605T1211,Jun5 0.325-0.349mg/mm bag ylw,BluePenES0323#16 0.335,0.335,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,70.0,2025-06-05,GHL_pyapp_20250605T1214,Jun5 0.325-0.349mg/mm bag ylw,ES0403#8 0.326,0.326,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,71.0,2025-06-05,GHL_pyapp_20250605T1218,Jun5 0.325-0.349mg/mm bag ylw,ES0402#11 0.342,0.342,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,72.0,2025-06-05,GHL_pyapp_20250605T1225,Jun5 0.325-0.349mg/mm bag ylw,ES0403#6 0.331,0.331,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,73.0,2025-06-05,GHL_pyapp_20250605T1228,Jun5 0.325-0.349mg/mm bag ylw,ES0403#19 0.329,0.329,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,74.0,2025-06-05,GHL_pyapp_20250605T1233,Jun5 0.325-0.349mg/mm bag ylw,ES0403#21 0.340,0.340,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,75.0,2025-06-05,GHL_pyapp_20250605T1301,Jun5 0.325-0.349mg/mm bag ylw,ES0403#30 0.345,0.345,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,76.0,2025-06-05,GHL_pyapp_20250605T1326,Jun5 0.325-0.349mg/mm bag ylw,ES0407#2 0.326,0.326,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,77.0,2025-06-05,GHL_pyapp_20250605T1330,Jun5 0.325-0.349mg/mm bag ylw,ES0331#31 0.334,0.334,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,78.0,2025-06-05,GHL_pyapp_20250605T1333,Jun5 0.325-0.349mg/mm bag ylw,ES0331#35 0.327,0.327,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,79.0,2025-06-05,GHL_pyapp_20250605T1336,Jun5 0.325-0.349mg/mm bag ylw,ES0401#4 0.325,0.325,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,80.0,2025-06-05,GHL_pyapp_20250605T1340,Jun5 0.325-0.349mg/mm bag ylw,ES0331#39 0.340,0.340,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,81.0,2025-06-05,GHL_pyapp_20250605T1344,Jun5 0.325-0.349mg/mm bag ylw,ES0331#49 0.348,0.348,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,82.0,2025-06-05,GHL_pyapp_20250605T1347,Jun5 0.325-0.349mg/mm bag ylw,ES0401#16 0.328,0.328,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,83.0,2025-06-05,GHL_pyapp_20250605T1350,Jun5 0.325-0.349mg/mm bag ylw,ES0401#17 0.328,0.328,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,84.0,2025-06-05,GHL_pyapp_20250605T1402,Jun5 0.325-0.349mg/mm bag ylw,ES0401#6 0.329,0.329,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,85.0,2025-06-05,GHL_pyapp_20250605T1407,Jun5 0.325-0.349mg/mm bag ylw,ES0328#21 0.334,0.334,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,86.0,2025-06-05,GHL_pyapp_20250605T1410,Jun5 0.325-0.349mg/mm bag ylw,0327#9 0.339,0.339,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,87.0,2025-06-05,GHL_pyapp_20250605T1414,Jun5 0.325-0.349mg/mm bag ylw,ES0328#18 0.329,0.329,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,88.0,2025-06-05,GHL_pyapp_20250605T1417,Jun5 0.325-0.349mg/mm bag ylw,ES0328#28 0.326,0.326,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,89.0,2025-06-05,GHL_pyapp_20250605T1422,Jun5 0.325-0.349mg/mm bag ylw,ES0328#30 0.334,0.334,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,90.0,2025-06-05,GHL_pyapp_20250605T1425,Jun5 0.325-0.349mg/mm bag ylw,BluePenES0325#21 0.325,0.325,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,91.0,2025-06-05,GHL_pyapp_20250605T1428,Jun5 0.325-0.349mg/mm bag ylw,ES0327#10 0.348,0.348,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,92.0,2025-06-05,GHL_pyapp_20250605T1431,Jun5 0.325-0.349mg/mm bag ylw,3-27#29 0.325,0.325,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,93.0,2025-06-05,GHL_pyapp_20250605T1437,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0401#3 0.375,0.375,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,94.0,2025-06-05,GHL_pyapp_20250605T1440,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0401#10 0.397,0.397,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,95.0,2025-06-05,GHL_pyapp_20250605T1443,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0401#13 0.376,0.376,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,96.0,2025-06-05,GHL_pyapp_20250605T1447,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0331#37 0.392,0.392,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,97.0,2025-06-05,GHL_pyapp_20250605T1450,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0331#34 0.386,0.386,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,98.0,2025-06-05,GHL_pyapp_20250605T1454,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0415#18 0.400,0.400,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,99.0,2025-06-05,GHL_pyapp_20250605T1457,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0415#14 0.383,0.383,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,100.0,2025-06-05,GHL_pyapp_20250605T1522,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0415#21 0.378,0.378,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,101.0,2025-06-05,GHL_pyapp_20250605T1528,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0410#22 0.397,0.397,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,102.0,2025-06-05,GHL_pyapp_20250605T1532,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0407#8 0.385,0.385,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,103.0,2025-06-05,GHL_pyapp_20250605T1536,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0404#2 0.377,0.377,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,104.0,2025-06-05,GHL_pyapp_20250605T1539,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0404#10 0.385,0.385,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,105.0,2025-06-05,GHL_pyapp_20250605T1542,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0403#23 0.377,0.377,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,106.0,2025-06-05,GHL_pyapp_20250605T1546,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0403#13 0.398,0.398,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,107.0,2025-06-05,GHL_pyapp_20250605T1557,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0403#12 0.391,0.391,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,108.0,2025-06-05,GHL_pyapp_20250605T1600,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0402#3 0.399,0.399,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,109.0,2025-06-05,GHL_pyapp_20250605T1605,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0331#5 0.373,0.373,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,110.0,2025-06-05,GHL_pyapp_20250605T1611,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0331#7 0.381,0.381,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,111.0,2025-06-05,GHL_pyapp_20250605T1615,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0415#3 0.379,0.379,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,112.0,2025-06-05,GHL_pyapp_20250605T1618,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0408#28 0.384,0.384,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,113.0,2025-06-05,GHL_pyapp_20250605T1621,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0403#4 0.392,0.392,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,114.0,2025-06-05,GHL_pyapp_20250605T1625,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0403#1BluMark 0.382,0.382,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,115.0,2025-06-05,GHL_pyapp_20250605T1628,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0403#7 0.383,0.383,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,116.0,2025-06-05,GHL_pyapp_20250605T1633,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0402#14 0.384,0.384,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,117.0,2025-06-05,GHL_pyapp_20250605T1636,Jun5 0.375-0.400mg/mm bag blu crossouts,ES0402#26 0.398,0.398,Vacuum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#%% Load OCT study information
octstudies = [];
folder_octexport_root = Path(r'\\file.corp.ghlabs.org\Shared\Projects\NAATOS\V1\NAATOS_OCT_WORK\OCTExport')
#folder_octexport_root = Path(r'D:\SGProjects\NAATOS\OCTlocal')

# Load list of data
for idx,record in dffilt.iterrows():
    octstudy = naatos_oct_tools.thorlabs_oct_file_reading.OCT_Study_Folder(record['Test name'],folder_octexport_root);
    octstudies.append(octstudy);

STUDY: GHL_pyapp_20250605T1211
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1214
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1218
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1225
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1228
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1233
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1301
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1326
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1330
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1333
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1336
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1340
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1344
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1347
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1350
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1402
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1407
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1410
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1414
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1417
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1422
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1425
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1428
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1431
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1437
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1440
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1443
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1447
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1450
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1454
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1457
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1522
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1528
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1532
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1536
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1539
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1542
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1546
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1557
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1600
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1605
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1611
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1615
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1618
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1621
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1625
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1628
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1633
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
STUDY: GHL_pyapp_20250605T1636
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}

In [6]:
# Master Parameters
oct_scalar_min = 30;
oct_scalar_max = 60;

In [7]:
#%% Load OCTSTUDY object, and start some processing on it
for idx,octstudy in enumerate(octstudies):
    octstudy : naatos_oct_tools.thorlabs_oct_file_reading.OCT_Study_Folder;
    print(octstudy)

    fname_merged_and_rescaled_volume = octstudy.folder_study_processed/'{:s}_STACKED_RESCALED_{:}to{:}_uint8.vtk'.format(octstudy.name,oct_scalar_min,oct_scalar_max);
    
    if(octstudy.study_info['study_num_oct_files']>0):
        # --Loading And Pre-Processing--
        if(fname_merged_and_rescaled_volume.exists()):
            pass;
            #print(f'Loading {fname_merged_and_rescaled_volume.name}')
            # Load the strip and merge into one volume
            #vdvol = vedo.Volume(pv.read(fname_merged_and_rescaled_volume));
            #octstudy.vdvol = vdvol;
        else:
            # Load OCT Data for this study
            octstudy.load_all_octs();


            # THESE WILL DO NOTHING IF ANTICIPATED OUTPUTS/ARTIFACTS ALREADY EXIST IN THE PROCESSED FOLDER

            # RGB Camera Images - Write them out as .jpg to processed folder
            naatos_oct_tools.oct_linear_scan_processing.process_rgbcamera_and_make_individual_images(octstudy);

            # RGB Camera Images - Make a montage and write out as .jpg to processed folder
            naatos_oct_tools.oct_linear_scan_processing.process_rgbcamera_and_make_montage_image(octstudy);
            #break;


            # IF MERGED STACKED AND RESCALED TO SCALAR RANGE FILE EXISTS, LOAD THAT; OTHERWISE PROCESS IT HERE
            octstudy.folder_study_processed.mkdir(exist_ok=True);
            fname = fname_merged_and_rescaled_volume;
            if(fname.exists()):
                print('Stacked volume byte-size .vtk file already exists, will not recreate.');
                print(fname);
            else:
                print(f'Generating merged and rescaled .vtk volume');
                # Generate merged and rescaled volume
                vdvol = octstudy.generate_merged_vdvol_and_rescaled(oct_scalar_min,oct_scalar_max);
                octstudy.vdvol = vdvol;
            
                # save this byte-adjusted volume
                vdvol.dataset.save(fname);
            
            # Unload OCT Data for this study (we will still keep the vdvol)
            octstudy.unload_all_octdata();

        # --Detailed Image Processing--
        if hasattr(octstudy,'vdvol'):
            del octstudy.vdvol;

<OCT_Study_Folder Object>
GHL_pyapp_20250605T1211 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1214 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1218 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1225 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1228 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1233 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1301 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1326 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1330 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1333 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1336 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1340 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1344 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1347 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1350 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1402 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1407 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1410 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1414 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1417 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1422 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1425 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1428 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1431 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1437 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1440 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1443 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1447 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1450 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1454 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1457 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1522 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1528 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1532 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1536 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1539 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1542 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1546 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1557 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1600 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1605 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1611 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1615 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1618 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1621 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1625 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1628 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1633 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}
<OCT_Study_Folder Object>
GHL_pyapp_20250605T1636 in folder //file.corp.ghlabs.org/Shared/Projects/NAATOS/V1/NAATOS_OCT_WORK/OCTExport
{   'study_has_an_ini_file': True,
    'study_has_json_info_file': True,
    'study_has_yat_log': False,
    'study_num_jpg_files': 0,
    'study_num_oct_files': 19,
    'study_num_vtk_files': 0}

# (util) delete some items from processed folder

In [ ]:
# Warning this can be destructive deleting processed data!!
if False:
    for idx,octstudy in enumerate(octstudies):
        print('~~~~~~~');
        print(octstudy.name);
        
        fname = (octstudy.folder_study_processed/'along_strip_data_extracted.hdf5')
        if(fname.exists()):
            print('deleted',fname.name);
            fname.unlink();

        # flist = octstudy.folder_study_processed.glob('figout*');
        # for fname in flist:
        #     print('deleted',fname.name);
        #     fname.unlink();

        # flist = octstudy.folder_study_processed.glob('processing_step*');
        # for fname in flist:
        #     print('deleted',fname.name);
        #     fname.unlink();

~~~~~~~
GHL_pyapp_20250605T1211
deleted along_strip_data_extracted.hdf5
deleted figout_post_maze_test.mp4
deleted figout_post_maze_test_connection_at_1990px.jpg
deleted figout_post_maze_test_connection_at_2100px.jpg
deleted figout_post_maze_test_connection_at_2630px.jpg
deleted figout_post_maze_test_connection_at_3105px.jpg
deleted figout_post_maze_test_connection_at_315px.jpg
deleted figout_post_maze_test_connection_at_3415px.jpg
deleted figout_post_maze_test_connection_at_5610px.jpg
deleted figout_post_maze_test_connection_at_5615px.jpg
deleted figout_post_maze_test_connection_at_5620px.jpg
deleted figout_post_maze_test_connection_at_5655px.jpg
deleted figout_post_maze_test_connection_at_5660px.jpg
deleted figout_post_maze_test_connection_at_5680px.jpg
deleted figout_post_maze_test_connection_at_5685px.jpg
deleted figout_post_maze_test_connection_at_5720px.jpg
deleted figout_post_maze_test_connection_at_6865px.jpg
deleted figout_post_maze_test_connection_at_6935px.jpg
deleted figout_stepA.mp4
deleted figout_stepB.mp4
deleted processing_step1a_20250605.jpg
deleted processing_step1a_20250606.jpg
deleted processing_step1b_20250605.jpg
deleted processing_step1b_20250606.jpg
deleted processing_step1c_20250605.jpg
deleted processing_step1c_20250606.jpg
deleted processing_step1d_20250605.jpg
deleted processing_step1d_20250606.jpg
deleted processing_step1e_20250605.jpg
deleted processing_step1e_20250606.jpg
deleted processing_step1f_20250605.jpg
deleted processing_step1f_20250606.jpg
~~~~~~~
GHL_pyapp_20250605T1214
deleted along_strip_data_extracted.hdf5
deleted figout_post_maze_test.mp4
deleted figout_post_maze_test_connection_at_3320px.jpg
deleted figout_post_maze_test_connection_at_5180px.jpg
deleted figout_post_maze_test_connection_at_7115px.jpg
deleted figout_post_maze_test_connection_at_7120px.jpg
deleted figout_stepA.mp4
deleted figout_stepB.mp4
deleted processing_step1a_20250606.jpg
deleted processing_step1b_20250606.jpg
deleted processing_step1c_20250606.jpg
deleted processing_step1d_20250606.jpg
deleted processing_step1e_20250606.jpg
deleted processing_step1f_20250605.jpg
deleted processing_step1f_20250606.jpg
~~~~~~~
GHL_pyapp_20250605T1218
deleted along_strip_data_extracted.hdf5
deleted figout_post_maze_test.mp4
deleted figout_post_maze_test_connection_at_1010px.jpg
deleted figout_post_maze_test_connection_at_1360px.jpg
deleted figout_post_maze_test_connection_at_1790px.jpg
deleted figout_post_maze_test_connection_at_1795px.jpg
deleted figout_post_maze_test_connection_at_2360px.jpg
deleted figout_post_maze_test_connection_at_2370px.jpg
deleted figout_post_maze_test_connection_at_3080px.jpg
deleted figout_post_maze_test_connection_at_3095px.jpg
deleted figout_post_maze_test_connection_at_320px.jpg
deleted figout_post_maze_test_connection_at_6920px.jpg
deleted figout_stepA.mp4
deleted figout_stepB.mp4
deleted processing_step1a_20250606.jpg
deleted processing_step1b_20250606.jpg
deleted processing_step1c_20250606.jpg
deleted processing_step1d_20250606.jpg
deleted processing_step1e_20250606.jpg
deleted processing_step1f_20250606.jpg
~~~~~~~
GHL_pyapp_20250605T1225
deleted along_strip_data_extracted.hdf5
deleted figout_post_maze_test.mp4
deleted figout_post_maze_test_connection_at_1080px.jpg
deleted figout_post_maze_test_connection_at_1340px.jpg
deleted figout_post_maze_test_connection_at_1480px.jpg
deleted figout_post_maze_test_connection_at_1825px.jpg
deleted figout_post_maze_test_connection_at_1830px.jpg
deleted figout_post_maze_test_connection_at_2385px.jpg
deleted figout_post_maze_test_connection_at_2405px.jpg
deleted figout_post_maze_test_connection_at_265px.jpg
deleted figout_post_maze_test_connection_at_2865px.jpg
deleted figout_post_maze_test_connection_at_290px.jpg
deleted figout_post_maze_test_connection_at_3450px.jpg
deleted figout_post_maze_test_connection_at_3470px.jpg
deleted figout_post_maze_test_connection_at_3475px.jpg
deleted figout_post_maze_test_connection_at_3500px.jpg
deleted figout_post_maze_test_connection_at_3540px.jpg
deleted figout_post_maze_test_connection_at_3545px.jpg
deleted figout_post_maze_test_connection_at_3570px.jpg
deleted figout_post_maze_test_connection_at_4075px.jpg
deleted figout_post_maze_test_connection_at_4615px.jpg
deleted figout_post_maze_test_connection_at_6150px.jpg
deleted figout_post_maze_test_connection_at_6605px.jpg
deleted figout_post_maze_test_connection_at_7050px.jpg
deleted figout_post_maze_test_connection_at_7815px.jpg
deleted figout_stepA.mp4
deleted figout_stepB.mp4
deleted processing_step1a_20250606.jpg
deleted processing_step1b_20250606.jpg
deleted processing_step1c_20250606.jpg
deleted processing_step1d_20250606.jpg
deleted processing_step1e_20250606.jpg
deleted processing_step1f_20250606.jpg
~~~~~~~
GHL_pyapp_20250605T1228
deleted along_strip_data_extracted.hdf5
deleted figout_post_maze_test.mp4
deleted figout_post_maze_test_connection_at_1700px.jpg
deleted figout_post_maze_test_connection_at_1715px.jpg
deleted figout_post_maze_test_connection_at_1935px.jpg
deleted figout_post_maze_test_connection_at_2155px.jpg
deleted figout_post_maze_test_connection_at_2330px.jpg
deleted figout_post_maze_test_connection_at_2335px.jpg
deleted figout_post_maze_test_connection_at_2340px.jpg
deleted figout_post_maze_test_connection_at_2345px.jpg
deleted figout_post_maze_test_connection_at_2855px.jpg
deleted figout_post_maze_test_connection_at_2925px.jpg
deleted figout_post_maze_test_connection_at_2990px.jpg
deleted figout_post_maze_test_connection_at_3245px.jpg
deleted figout_post_maze_test_connection_at_50px.jpg
deleted figout_post_maze_test_connection_at_675px.jpg
deleted figout_stepA.mp4
deleted figout_stepB.mp4
deleted processing_step1a_20250606.jpg
deleted processing_step1b_20250606.jpg
deleted processing_step1c_20250606.jpg
deleted processing_step1d_20250606.jpg
deleted processing_step1e_20250606.jpg
deleted processing_step1f_20250606.jpg
~~~~~~~
GHL_pyapp_20250605T1233
deleted along_strip_data_extracted.hdf5
deleted figout_post_maze_test.mp4
deleted figout_post_maze_test_connection_at_2695px.jpg
deleted figout_post_maze_test_connection_at_3460px.jpg
deleted figout_post_maze_test_connection_at_3800px.jpg
deleted figout_post_maze_test_connection_at_4920px.jpg
deleted figout_stepA.mp4
deleted figout_stepB.mp4
deleted processing_step1a_20250606.jpg
deleted processing_step1b_20250606.jpg
deleted processing_step1c_20250606.jpg
deleted processing_step1d_20250606.jpg
deleted processing_step1e_20250606.jpg
deleted processing_step1f_20250606.jpg
~~~~~~~
GHL_pyapp_20250605T1301
deleted along_strip_data_extracted.hdf5
deleted figout_post_maze_test.mp4
deleted figout_post_maze_test_connection_at_1005px.jpg
deleted figout_post_maze_test_connection_at_1205px.jpg
deleted figout_post_maze_test_connection_at_2895px.jpg
deleted figout_post_maze_test_connection_at_2925px.jpg
deleted figout_post_maze_test_connection_at_315px.jpg
deleted figout_post_maze_test_connection_at_3330px.jpg
deleted figout_post_maze_test_connection_at_350px.jpg
deleted figout_post_maze_test_connection_at_3530px.jpg
deleted figout_post_maze_test_connection_at_3580px.jpg
deleted figout_post_maze_test_connection_at_3585px.jpg
deleted figout_post_maze_test_connection_at_3775px.jpg
deleted figout_post_maze_test_connection_at_3780px.jpg
deleted figout_post_maze_test_connection_at_3785px.jpg
deleted figout_post_maze_test_connection_at_3790px.jpg
deleted figout_post_maze_test_connection_at_3795px.jpg
deleted figout_post_maze_test_connection_at_3970px.jpg
deleted figout_post_maze_test_connection_at_4290px.jpg
deleted figout_post_maze_test_connection_at_4295px.jpg
deleted figout_post_maze_test_connection_at_4425px.jpg
deleted figout_post_maze_test_connection_at_4465px.jpg
deleted figout_post_maze_test_connection_at_4495px.jpg
deleted figout_post_maze_test_connection_at_4500px.jpg
deleted figout_post_maze_test_connection_at_4505px.jpg
deleted figout_post_maze_test_connection_at_4540px.jpg
deleted figout_post_maze_test_connection_at_4545px.jpg
deleted figout_post_maze_test_connection_at_4650px.jpg
deleted figout_post_maze_test_connection_at_5070px.jpg
deleted figout_post_maze_test_connection_at_5450px.jpg
deleted figout_post_maze_test_connection_at_5475px.jpg
deleted figout_post_maze_test_connection_at_5485px.jpg
deleted figout_post_maze_test_connection_at_6145px.jpg
deleted figout_post_maze_test_connection_at_6690px.jpg
deleted figout_post_maze_test_connection_at_6775px.jpg
deleted figout_post_maze_test_connection_at_7010px.jpg
deleted figout_post_maze_test_connection_at_8030px.jpg
deleted figout_post_maze_test_connection_at_8035px.jpg
deleted figout_post_maze_test_connection_at_985px.jpg
deleted figout_post_maze_test_connection_at_995px.jpg
deleted figout_stepA.mp4
deleted figout_stepB.mp4
deleted processing_step1a_20250606.jpg
deleted processing_step1b_20250606.jpg
deleted processing_step1c_20250606.jpg
deleted processing_step1d_20250606.jpg
deleted processing_step1e_20250606.jpg
deleted processing_step1f_20250606.jpg
~~~~~~~
GHL_pyapp_20250605T1326
deleted along_strip_data_extracted.hdf5
deleted figout_post_maze_test.mp4
deleted figout_post_maze_test_connection_at_2225px.jpg
deleted figout_post_maze_test_connection_at_2230px.jpg
deleted figout_post_maze_test_connection_at_2235px.jpg
deleted figout_post_maze_test_connection_at_2240px.jpg
deleted figout_post_maze_test_connection_at_2255px.jpg
deleted figout_post_maze_test_connection_at_225px.jpg
deleted figout_post_maze_test_connection_at_2260px.jpg
deleted figout_post_maze_test_connection_at_2265px.jpg
deleted figout_post_maze_test_connection_at_2275px.jpg
deleted figout_post_maze_test_connection_at_2310px.jpg
deleted figout_post_maze_test_connection_at_2315px.jpg
deleted figout_post_maze_test_connection_at_2320px.jpg
deleted figout_post_maze_test_connection_at_2330px.jpg
deleted figout_post_maze_test_connection_at_2335px.jpg
deleted figout_post_maze_test_connection_at_2355px.jpg
deleted figout_post_maze_test_connection_at_2360px.jpg
deleted figout_post_maze_test_connection_at_2365px.jpg
deleted figout_post_maze_test_connection_at_2370px.jpg
deleted figout_post_maze_test_connection_at_2475px.jpg
deleted figout_post_maze_test_connection_at_2495px.jpg
deleted figout_post_maze_test_connection_at_2510px.jpg
deleted figout_post_maze_test_connection_at_2515px.jpg
deleted figout_post_maze_test_connection_at_2930px.jpg
deleted figout_post_maze_test_connection_at_3010px.jpg
deleted figout_post_maze_test_connection_at_3035px.jpg
deleted figout_post_maze_test_connection_at_3970px.jpg
deleted figout_post_maze_test_connection_at_4725px.jpg
deleted figout_post_maze_test_connection_at_6450px.jpg
deleted figout_post_maze_test_connection_at_6455px.jpg
deleted figout_post_maze_test_connection_at_6485px.jpg
deleted figout_post_maze_test_connection_at_7010px.jpg
deleted figout_post_maze_test_connection_at_7880px.jpg
deleted figout_stepA.mp4
deleted figout_stepB.mp4
deleted processing_step1a_20250606.jpg
deleted processing_step1b_20250606.jpg
deleted processing_step1c_20250606.jpg
deleted processing_step1d_20250606.jpg
deleted processing_step1e_20250606.jpg
deleted processing_step1f_20250606.jpg
~~~~~~~
GHL_pyapp_20250605T1330
deleted along_strip_data_extracted.hdf5
deleted figout_post_maze_test.mp4
deleted figout_post_maze_test_connection_at_1130px.jpg
deleted figout_post_maze_test_connection_at_1595px.jpg
deleted figout_post_maze_test_connection_at_15px.jpg
deleted figout_post_maze_test_connection_at_1820px.jpg
deleted figout_post_maze_test_connection_at_1825px.jpg
deleted figout_post_maze_test_connection_at_1830px.jpg
deleted figout_post_maze_test_connection_at_1835px.jpg
deleted figout_post_maze_test_connection_at_4020px.jpg
deleted figout_post_maze_test_connection_at_425px.jpg
deleted figout_post_maze_test_connection_at_685px.jpg
deleted figout_post_maze_test_connection_at_740px.jpg
deleted figout_post_maze_test_connection_at_770px.jpg
deleted figout_post_maze_test_connection_at_775px.jpg
deleted figout_post_maze_test_connection_at_880px.jpg
deleted figout_post_maze_test_connection_at_940px.jpg
deleted figout_stepA.mp4
deleted figout_stepB.mp4
deleted processing_step1a_20250606.jpg
deleted processing_step1b_20250606.jpg
deleted processing_step1c_20250606.jpg
deleted processing_step1d_20250606.jpg
deleted processing_step1e_20250606.jpg
deleted processing_step1f_20250606.jpg
~~~~~~~
GHL_pyapp_20250605T1333
deleted along_strip_data_extracted.hdf5
deleted figout_post_maze_test_connection_at_1180px.jpg
deleted figout_post_maze_test_connection_at_1815px.jpg
deleted figout_post_maze_test_connection_at_1825px.jpg
deleted figout_post_maze_test_connection_at_1850px.jpg
deleted figout_post_maze_test_connection_at_1900px.jpg
deleted figout_post_maze_test_connection_at_1915px.jpg
deleted figout_post_maze_test_connection_at_1940px.jpg
deleted figout_post_maze_test_connection_at_1945px.jpg
deleted figout_post_maze_test_connection_at_1950px.jpg
deleted figout_post_maze_test_connection_at_20px.jpg
deleted figout_post_maze_test_connection_at_3065px.jpg
deleted figout_post_maze_test_connection_at_3155px.jpg
deleted figout_post_maze_test_connection_at_3170px.jpg
deleted figout_post_maze_test_connection_at_3175px.jpg
deleted figout_post_maze_test_connection_at_3260px.jpg
deleted figout_post_maze_test_connection_at_395px.jpg
deleted figout_post_maze_test_connection_at_3960px.jpg
deleted figout_post_maze_test_connection_at_400px.jpg
deleted figout_post_maze_test_connection_at_4030px.jpg
deleted figout_post_maze_test_connection_at_4035px.jpg
deleted figout_post_maze_test_connection_at_4530px.jpg
deleted figout_post_maze_test_connection_at_4550px.jpg
deleted figout_post_maze_test_connection_at_4560px.jpg
deleted figout_post_maze_test_connection_at_4565px.jpg
deleted figout_post_maze_test_connection_at_4570px.jpg
deleted figout_post_maze_test_connection_at_45px.jpg
deleted figout_post_maze_test_connection_at_4775px.jpg
deleted figout_post_maze_test_connection_at_4790px.jpg
deleted figout_post_maze_test_connection_at_4795px.jpg
deleted figout_post_maze_test_connection_at_4805px.jpg
deleted figout_post_maze_test_connection_at_4845px.jpg
deleted figout_post_maze_test_connection_at_4850px.jpg
deleted figout_post_maze_test_connection_at_4855px.jpg
deleted figout_post_maze_test_connection_at_4990px.jpg
deleted figout_post_maze_test_connection_at_4995px.jpg
deleted figout_post_maze_test_connection_at_5000px.jpg
deleted figout_post_maze_test_connection_at_5050px.jpg
deleted figout_post_maze_test_connection_at_5055px.jpg
deleted figout_post_maze_test_connection_at_5060px.jpg
deleted figout_post_maze_test_connection_at_5095px.jpg
deleted figout_post_maze_test_connection_at_5165px.jpg
deleted figout_post_maze_test_connection_at_5205px.jpg
deleted figout_post_maze_test_connection_at_810px.jpg
deleted figout_stepA.mp4
deleted figout_stepB.mp4
deleted processing_step1a_20250606.jpg
deleted processing_step1b_20250606.jpg
deleted processing_step1c_20250606.jpg
deleted processing_step1d_20250606.jpg
deleted processing_step1e_20250606.jpg
deleted processing_step1f_20250606.jpg
~~~~~~~
GHL_pyapp_20250605T1336
deleted along_strip_data_extracted.hdf5
deleted figout_stepA.mp4
deleted processing_step1a_20250606.jpg
deleted processing_step1b_20250606.jpg
deleted processing_step1c_20250606.jpg
deleted processing_step1d_20250606.jpg
deleted processing_step1e_20250606.jpg
deleted processing_step1f_20250606.jpg
~~~~~~~
GHL_pyapp_20250605T1340
deleted along_strip_data_extracted.hdf5
deleted figout_stepA.mp4
deleted processing_step1a_20250606.jpg
deleted processing_step1b_20250606.jpg
deleted processing_step1c_20250606.jpg
deleted processing_step1d_20250606.jpg
deleted processing_step1e_20250606.jpg
deleted processing_step1f_20250606.jpg
~~~~~~~
GHL_pyapp_20250605T1344
deleted processing_step1a_20250606.jpg
deleted processing_step1b_20250606.jpg
deleted processing_step1c_20250606.jpg
deleted processing_step1d_20250606.jpg
deleted processing_step1e_20250606.jpg
deleted processing_step1f_20250606.jpg
~~~~~~~
GHL_pyapp_20250605T1347
deleted processing_step1a_20250606.jpg
deleted processing_step1b_20250606.jpg
deleted processing_step1c_20250606.jpg
deleted processing_step1d_20250606.jpg
deleted processing_step1e_20250606.jpg
deleted processing_step1f_20250606.jpg
~~~~~~~
GHL_pyapp_20250605T1350
deleted processing_step1a_20250606.jpg
deleted processing_step1b_20250606.jpg
deleted processing_step1c_20250606.jpg
deleted processing_step1d_20250606.jpg
deleted processing_step1e_20250606.jpg
deleted processing_step1f_20250606.jpg
~~~~~~~
GHL_pyapp_20250605T1402
deleted processing_step1a_20250606.jpg
deleted processing_step1b_20250606.jpg
deleted processing_step1c_20250606.jpg
deleted processing_step1d_20250606.jpg
deleted processing_step1e_20250606.jpg
deleted processing_step1f_20250606.jpg
~~~~~~~
GHL_pyapp_20250605T1407
~~~~~~~
GHL_pyapp_20250605T1410
~~~~~~~
GHL_pyapp_20250605T1414
~~~~~~~
GHL_pyapp_20250605T1417
~~~~~~~
GHL_pyapp_20250605T1422
~~~~~~~
GHL_pyapp_20250605T1425
~~~~~~~
GHL_pyapp_20250605T1428
~~~~~~~
GHL_pyapp_20250605T1431
~~~~~~~
GHL_pyapp_20250605T1437
~~~~~~~
GHL_pyapp_20250605T1440
~~~~~~~
GHL_pyapp_20250605T1443
~~~~~~~
GHL_pyapp_20250605T1447
~~~~~~~
GHL_pyapp_20250605T1450
~~~~~~~
GHL_pyapp_20250605T1454
~~~~~~~
GHL_pyapp_20250605T1457
~~~~~~~
GHL_pyapp_20250605T1522
~~~~~~~
GHL_pyapp_20250605T1528
~~~~~~~
GHL_pyapp_20250605T1532
~~~~~~~
GHL_pyapp_20250605T1536
~~~~~~~
GHL_pyapp_20250605T1539
~~~~~~~
GHL_pyapp_20250605T1542
~~~~~~~
GHL_pyapp_20250605T1546
~~~~~~~
GHL_pyapp_20250605T1557
~~~~~~~
GHL_pyapp_20250605T1600
~~~~~~~
GHL_pyapp_20250605T1605
~~~~~~~
GHL_pyapp_20250605T1611
~~~~~~~
GHL_pyapp_20250605T1615
~~~~~~~
GHL_pyapp_20250605T1618
~~~~~~~
GHL_pyapp_20250605T1621
~~~~~~~
GHL_pyapp_20250605T1625
~~~~~~~
GHL_pyapp_20250605T1628
~~~~~~~
GHL_pyapp_20250605T1633
~~~~~~~
GHL_pyapp_20250605T1636

# Call Notebooks - Processing A to D and E

In [9]:
#%% Load OCTSTUDY object, and start some processing on it
octstudies_to_run = [];
norunlist = [
    #'GHL_pyapp_20250508T1112','GHL_pyapp_20250508T1128','GHL_pyapp_20250508T1134','GHL_pyapp_20250508T1143'
]
forcerunlist = [
    #'GHL_pyapp_20250508T1151',
    #'GHL_pyapp_20250508T1601',
    #'GHL_pyapp_20250508T1608',
]
for idx,octstudy in enumerate(octstudies):
    octstudy : naatos_oct_tools.thorlabs_oct_file_reading.OCT_Study_Folder;
    print('~~~~~~~');
    print(octstudy.name);
    rescheck = octstudy.resultsCheck();
    pp.pprint(rescheck)
    doWeRunTheNotebook = any([v is False for k,v in rescheck.items()])
    doWeRunTheNotebook = doWeRunTheNotebook or ('/dfstepE' not in rescheck['along_strip_data_extracted']);
    print('Run?',doWeRunTheNotebook)
    if((doWeRunTheNotebook and octstudy.name not in norunlist) or (octstudy.name in forcerunlist)):
        octstudies_to_run.append(octstudy);
    # if(octstudy.name in forcerunlist):
    #     octstudies_to_run.append(octstudy);

# if(len(octstudies_to_run)>4):
#     #octstudies_to_run=octstudies_to_run[0:4];
#     #octstudies_to_run=octstudies_to_run[-4:];
#     print('only a subset');
#     norunlist = [
#         'GHL_pyapp_20250508T1112','GHL_pyapp_20250508T1128','GHL_pyapp_20250508T1134','GHL_pyapp_20250508T1143'
#     ]
#     octstudies_to_run = [s for s in octstudies_to_run if s.name not in norunlist ]
#     pass;

#octstudies_to_run = octstudies_to_run[0:20];

print('~~~~~~~');
print('We will run the processing on {:} octstudies.'.format(len(octstudies_to_run)))
print([x.name for x in octstudies_to_run])

~~~~~~~
GHL_pyapp_20250605T1211
{   'along_strip_data_extracted': False,
    'exist_data_extracted': True,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1214
{   'along_strip_data_extracted': False,
    'exist_data_extracted': True,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1218
{   'along_strip_data_extracted': False,
    'exist_data_extracted': True,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1225
{   'along_strip_data_extracted': False,
    'exist_data_extracted': True,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1228
{   'along_strip_data_extracted': False,
    'exist_data_extracted': True,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1233
{   'along_strip_data_extracted': False,
    'exist_data_extracted': True,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1301
{   'along_strip_data_extracted': False,
    'exist_data_extracted': True,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1326
{   'along_strip_data_extracted': False,
    'exist_data_extracted': True,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1330
{   'along_strip_data_extracted': False,
    'exist_data_extracted': True,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1333
{   'along_strip_data_extracted': False,
    'exist_data_extracted': True,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1336
{   'along_strip_data_extracted': False,
    'exist_data_extracted': True,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1340
{   'along_strip_data_extracted': False,
    'exist_data_extracted': True,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1344
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1347
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1350
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1402
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1407
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1410
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1414
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1417
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1422
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1425
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1428
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1431
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1437
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1440
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1443
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1447
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1450
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1454
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1457
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1522
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1528
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1532
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1536
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1539
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1542
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1546
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1557
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1600
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1605
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1611
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1615
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1618
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1621
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1625
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1628
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1633
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
GHL_pyapp_20250605T1636
{   'along_strip_data_extracted': False,
    'exist_data_extracted': False,
    'figoutmp4_mazetest': False,
    'figoutmp4_stepA': False,
    'figoutmp4_stepB': False}
Run? True
~~~~~~~
We will run the processing on 49 octstudies.
['GHL_pyapp_20250605T1211', 'GHL_pyapp_20250605T1214', 'GHL_pyapp_20250605T1218', 'GHL_pyapp_20250605T1225', 'GHL_pyapp_20250605T1228', 'GHL_pyapp_20250605T1233', 'GHL_pyapp_20250605T1301', 'GHL_pyapp_20250605T1326', 'GHL_pyapp_20250605T1330', 'GHL_pyapp_20250605T1333', 'GHL_pyapp_20250605T1336', 'GHL_pyapp_20250605T1340', 'GHL_pyapp_20250605T1344', 'GHL_pyapp_20250605T1347', 'GHL_pyapp_20250605T1350', 'GHL_pyapp_20250605T1402', 'GHL_pyapp_20250605T1407', 'GHL_pyapp_20250605T1410', 'GHL_pyapp_20250605T1414', 'GHL_pyapp_20250605T1417', 'GHL_pyapp_20250605T1422', 'GHL_pyapp_20250605T1425', 'GHL_pyapp_20250605T1428', 'GHL_pyapp_20250605T1431', 'GHL_pyapp_20250605T1437', 'GHL_pyapp_20250605T1440', 'GHL_pyapp_20250605T1443', 'GHL_pyapp_20250605T1447', 'GHL_pyapp_20250605T1450', 'GHL_pyapp_20250605T1454', 'GHL_pyapp_20250605T1457', 'GHL_pyapp_20250605T1522', 'GHL_pyapp_20250605T1528', 'GHL_pyapp_20250605T1532', 'GHL_pyapp_20250605T1536', 'GHL_pyapp_20250605T1539', 'GHL_pyapp_20250605T1542', 'GHL_pyapp_20250605T1546', 'GHL_pyapp_20250605T1557', 'GHL_pyapp_20250605T1600', 'GHL_pyapp_20250605T1605', 'GHL_pyapp_20250605T1611', 'GHL_pyapp_20250605T1615', 'GHL_pyapp_20250605T1618', 'GHL_pyapp_20250605T1621', 'GHL_pyapp_20250605T1625', 'GHL_pyapp_20250605T1628', 'GHL_pyapp_20250605T1633', 'GHL_pyapp_20250605T1636']

# Prepare notebooks we will call

In [11]:
#nbpath = r"C:\Users\SimonGhionea\OneDrive - Global Health Labs, Inc\ProjectsCloud\NAATOS\sgpyanalysisoct\sandbox_sg\nb_test_nbparams.ipynb";
#nbpath = r"C:\Users\SimonGhionea\OneDrive - Global Health Labs, Inc\ProjectsCloud\NAATOS\sgpyanalysisoct\sandbox_sg\octproc_20250429_process_a_longstrip.ipynb";
nbpaths = [
    r"C:\Users\SimonGhionea\OneDrive - Global Health Labs, Inc\ProjectsCloud\NAATOS\sgpyanalysisoct\sandbox_sg\octproc_20250606_process_a_longstrip.ipynb",
    r"C:\Users\SimonGhionea\OneDrive - Global Health Labs, Inc\ProjectsCloud\NAATOS\sgpyanalysisoct\sandbox_sg\octproc_20250507_process_E_longstripmetric.ipynb"
];
for nbpath in nbpaths:
    print('Notebook:',Path(nbpath).name);
    parameters = papermill.inspect_notebook(nbpath)
    pp.pprint(parameters.keys());

Notebook: octproc_20250606_process_a_longstrip.ipynb
dict_keys(['oct_scalar_min', 'oct_scalar_max', 'codename', 'study_name', 'folder_octexport_root', 'folder_figure_temp'])
Notebook: octproc_20250507_process_E_longstripmetric.ipynb
dict_keys(['oct_scalar_min', 'oct_scalar_max', 'codename', 'folder_octexport_root', 'study_name', 'folder_figure_temp'])

# Call notebooks to process (Multiple-strips in parallel, concurrent futures)

In [12]:
import concurrent.futures

def run_notebook_on_an_octstudy(octstudy : naatos_oct_tools.thorlabs_oct_file_reading.OCT_Study_Folder):

    folder_temp_path = Path(r'D:\TEMP\OCTtmp');
    folder_temp_path.mkdir(parents=True,exist_ok=True);

    # run each notebook we have defined to be run
    nnotebooks = len(nbpaths);
    for count,nbpath in enumerate(nbpaths):
        nbpath = Path(nbpath)
        nbpath_out = folder_temp_path/(nbpath.stem+'_OUT_{:s}.ipynb').format(octstudy.name)

        # execute a notebook
        print(f'Launching for {octstudy.name} the {count+1}/{nnotebooks} notebook {nbpath.name} ...')
        try:
            papermill.execute_notebook(
                input_path=nbpath,
                output_path=nbpath_out,
                parameters=dict(
                    folder_octexport_root=folder_octexport_root.as_posix(),
                    codename = Path(nbpath).name,
                    study_name=octstudy.name,
                    folder_figure_temp=nbpath_out.parent.as_posix()
                )
            )
            print(f'Finished for {octstudy.name} the {count+1}/{nnotebooks} notebook {nbpath.name} !')
        except Exception as e:
            print(f'FAILED for {octstudy.name} the {count+1}/{nnotebooks} notebook {nbpath.name} !')
            break;
    print(f'alldone for {octstudy.name}')


# Using concurrent.futures to handle multiprocessing
def run_in_parallel(num_processes):
    # with concurrent.futures.ProcessPoolExecutor(max_workers=num_processes) as executor:
    #     futures = [executor.submit(run_notebook_on_an_octstudy, octstudy) for octstudy in octstudies_to_run]
    #     for future in concurrent.futures.as_completed(futures):
    #         print(future.result())  # You can handle results or exceptions here
    with concurrent.futures.ThreadPoolExecutor(max_workers=num_processes) as executor:
        futures = [executor.submit(run_notebook_on_an_octstudy, octstudy) for octstudy in octstudies_to_run]
        for future in concurrent.futures.as_completed(futures):
            print(future.result());

# Example usage
num_processes = 8;  # Number of parallel processes
run_in_parallel(num_processes);

Launching for GHL_pyapp_20250605T1211 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...
Launching for GHL_pyapp_20250605T1214 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...
Launching for GHL_pyapp_20250605T1218 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...
Launching for GHL_pyapp_20250605T1225 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...
Launching for GHL_pyapp_20250605T1228 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...
Launching for GHL_pyapp_20250605T1233 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...
Launching for GHL_pyapp_20250605T1301 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...
Launching for GHL_pyapp_20250605T1326 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

FAILED for GHL_pyapp_20250605T1211 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
alldone for GHL_pyapp_20250605T1211
None
Launching for GHL_pyapp_20250605T1330 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

FAILED for GHL_pyapp_20250605T1301 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
alldone for GHL_pyapp_20250605T1301
Launching for GHL_pyapp_20250605T1333 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...
None

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

FAILED for GHL_pyapp_20250605T1333 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
alldone for GHL_pyapp_20250605T1333
None
Launching for GHL_pyapp_20250605T1336 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

FAILED for GHL_pyapp_20250605T1336 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
alldone for GHL_pyapp_20250605T1336
None
Launching for GHL_pyapp_20250605T1340 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Autosave too slow: 8.20 sec, over 25% limit. Backing off to 60 sec
Autosave too slow: 12.28 sec, over 25% limit. Backing off to 60 sec
Autosave too slow: 35.61 sec, over 25% limit. Backing off to 60 sec
Autosave too slow: 34.05 sec, over 25% limit. Backing off to 60 sec
Autosave too slow: 31.42 sec, over 25% limit. Backing off to 60 sec
Autosave too slow: 15.92 sec, over 25% limit. Backing off to 60 sec
Autosave too slow: 154.70 sec, over 25% limit. Backing off to 120 sec
Autosave too slow: 153.49 sec, over 25% limit. Backing off to 120 sec
Autosave too slow: 153.70 sec, over 25% limit. Backing off to 120 sec
Autosave too slow: 81.08 sec, over 25% limit. Backing off to 240 sec
Autosave too slow: 65.02 sec, over 25% limit. Backing off to 240 sec
Autosave too slow: 17.72 sec, over 25% limit. Backing off to 60 sec
Autosave too slow: 16.55 sec, over 25% limit. Backing off to 120 sec

Finished for GHL_pyapp_20250605T1218 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1218 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1326 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1326 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1228 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1228 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1330 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1330 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Autosave too slow: 10.47 sec, over 25% limit. Backing off to 60 sec
Autosave too slow: 10.27 sec, over 25% limit. Backing off to 60 sec

Finished for GHL_pyapp_20250605T1214 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1214 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1225 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1225 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1218 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1218
Launching for GHL_pyapp_20250605T1344 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...
None

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1330 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1330
None
Launching for GHL_pyapp_20250605T1347 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1233 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1233 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1326 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1326
None
Launching for GHL_pyapp_20250605T1350 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1225 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1225
None
Launching for GHL_pyapp_20250605T1402 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1214 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1214
None
Launching for GHL_pyapp_20250605T1407 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1233 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1233
None
Launching for GHL_pyapp_20250605T1410 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1228 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1228
None
Launching for GHL_pyapp_20250605T1414 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

FAILED for GHL_pyapp_20250605T1402 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
alldone for GHL_pyapp_20250605T1402
None
Launching for GHL_pyapp_20250605T1417 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1340 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1340 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1340 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1340
Launching for GHL_pyapp_20250605T1422 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...
None

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Autosave too slow: 8.52 sec, over 25% limit. Backing off to 60 sec
Autosave too slow: 9.78 sec, over 25% limit. Backing off to 60 sec
Autosave too slow: 9.32 sec, over 25% limit. Backing off to 60 sec

FAILED for GHL_pyapp_20250605T1422 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
alldone for GHL_pyapp_20250605T1422
None
Launching for GHL_pyapp_20250605T1425 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1350 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1350 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1407 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1407 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1407 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1407
None
Launching for GHL_pyapp_20250605T1428 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1350 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1350
None
Launching for GHL_pyapp_20250605T1431 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1410 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1410 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1344 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1344 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1347 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1347 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1417 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1417 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1410 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1410
None
Launching for GHL_pyapp_20250605T1437 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1414 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1414 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Autosave too slow: 9.08 sec, over 25% limit. Backing off to 60 sec
Autosave too slow: 7.99 sec, over 25% limit. Backing off to 60 sec
Autosave too slow: 8.53 sec, over 25% limit. Backing off to 60 sec

Finished for GHL_pyapp_20250605T1344 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1344
None
Launching for GHL_pyapp_20250605T1440 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

FAILED for GHL_pyapp_20250605T1440 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
alldone for GHL_pyapp_20250605T1440
None
Launching for GHL_pyapp_20250605T1443 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1417 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1417
Launching for GHL_pyapp_20250605T1447 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...
None

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1347 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1347
None
Launching for GHL_pyapp_20250605T1450 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1425 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1425 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1414 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1414
None
Launching for GHL_pyapp_20250605T1454 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1428 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1428 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Autosave too slow: 7.67 sec, over 25% limit. Backing off to 60 sec

Finished for GHL_pyapp_20250605T1431 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1431 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1425 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1425
Launching for GHL_pyapp_20250605T1457 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...
None

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1437 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1437 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

FAILED for GHL_pyapp_20250605T1457 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
alldone for GHL_pyapp_20250605T1457
None
Launching for GHL_pyapp_20250605T1522 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

FAILED for GHL_pyapp_20250605T1522 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
alldone for GHL_pyapp_20250605T1522
None
Launching for GHL_pyapp_20250605T1528 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1428 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1428
None
Launching for GHL_pyapp_20250605T1532 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1431 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1431
None
Launching for GHL_pyapp_20250605T1536 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

FAILED for GHL_pyapp_20250605T1536 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
alldone for GHL_pyapp_20250605T1536
None
Launching for GHL_pyapp_20250605T1539 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

FAILED for GHL_pyapp_20250605T1539 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
alldone for GHL_pyapp_20250605T1539
None
Launching for GHL_pyapp_20250605T1542 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1443 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1443 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1437 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1437
None
Launching for GHL_pyapp_20250605T1546 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1443 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1443
Launching for GHL_pyapp_20250605T1557 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...
None

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Autosave too slow: 9.00 sec, over 25% limit. Backing off to 60 sec

Finished for GHL_pyapp_20250605T1447 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1447 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1450 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1450 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1454 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1454 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Autosave too slow: 8.62 sec, over 25% limit. Backing off to 60 sec

FAILED for GHL_pyapp_20250605T1528 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
alldone for GHL_pyapp_20250605T1528
None
Launching for GHL_pyapp_20250605T1600 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Autosave too slow: 11.88 sec, over 25% limit. Backing off to 60 sec

Finished for GHL_pyapp_20250605T1450 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1450
None
Launching for GHL_pyapp_20250605T1605 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1447 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1447
None
Launching for GHL_pyapp_20250605T1611 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1454 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1454
None
Launching for GHL_pyapp_20250605T1615 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Autosave too slow: 8.82 sec, over 25% limit. Backing off to 60 sec

Finished for GHL_pyapp_20250605T1532 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1532 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Autosave too slow: 10.78 sec, over 25% limit. Backing off to 60 sec

Finished for GHL_pyapp_20250605T1542 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1542 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Autosave too slow: 7.52 sec, over 25% limit. Backing off to 60 sec

Finished for GHL_pyapp_20250605T1532 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1532
Launching for GHL_pyapp_20250605T1618 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...
None

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Autosave too slow: 10.50 sec, over 25% limit. Backing off to 60 sec

Finished for GHL_pyapp_20250605T1542 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1542
None
Launching for GHL_pyapp_20250605T1621 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Autosave too slow: 9.17 sec, over 25% limit. Backing off to 60 sec

Finished for GHL_pyapp_20250605T1557 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1557 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1546 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1546 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1600 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1600 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1605 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1605 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Autosave too slow: 9.42 sec, over 25% limit. Backing off to 60 sec
Autosave too slow: 9.26 sec, over 25% limit. Backing off to 60 sec

Finished for GHL_pyapp_20250605T1611 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1611 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1600 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1600
None
Launching for GHL_pyapp_20250605T1625 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

FAILED for GHL_pyapp_20250605T1625 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
alldone for GHL_pyapp_20250605T1625
None
Launching for GHL_pyapp_20250605T1628 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

FAILED for GHL_pyapp_20250605T1628 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
alldone for GHL_pyapp_20250605T1628
None
Launching for GHL_pyapp_20250605T1633 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1615 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1615 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1546 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1546
None
Launching for GHL_pyapp_20250605T1636 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb ...

Executing:   0%|          | 0/53 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1605 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1605
None
Finished for GHL_pyapp_20250605T1611 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1611
None
Finished for GHL_pyapp_20250605T1557 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1557
None
Finished for GHL_pyapp_20250605T1618 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1618 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1615 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1615
None
Finished for GHL_pyapp_20250605T1618 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1618
None
Finished for GHL_pyapp_20250605T1621 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1621 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1621 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1621
None
Finished for GHL_pyapp_20250605T1633 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1633 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1636 the 1/2 notebook octproc_20250606_process_a_longstrip.ipynb !
Launching for GHL_pyapp_20250605T1636 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb ...

Executing:   0%|          | 0/19 [00:00<?, ?cell/s]

Finished for GHL_pyapp_20250605T1633 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1633
None
Finished for GHL_pyapp_20250605T1636 the 2/2 notebook octproc_20250507_process_E_longstripmetric.ipynb !
alldone for GHL_pyapp_20250605T1636
None

In [ ]:
import concurrent.futures
import time

def task(n):
    time.sleep(1)
    return n * n

# Using ThreadPoolExecutor
with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
    futures = [executor.submit(task, i) for i in range(10)]
    for future in concurrent.futures.as_completed(futures):
        print(future.result())

# # Using ProcessPoolExecutor
# with concurrent.futures.ProcessPoolExecutor(max_workers=5) as executor:
#     results = executor.map(task, range(10))
#     for result in results:
#         print(result)

# Call Notebooks - Processing E

In [ ]:
#%% Load OCTSTUDY object, and start some processing on it
octstudies_to_run = [];
for idx,octstudy in enumerate(octstudies):
    octstudy : naatos_oct_tools.thorlabs_oct_file_reading.OCT_Study_Folder;
    print('~~~~~~~');
    print(octstudy.name);
    rescheck = octstudy.resultsCheck();
    pp.pprint(rescheck);
    doWeRunTheNotebook = not any([v is False for k,v in rescheck.items()])
    doWeRunTheNotebook = doWeRunTheNotebook and ('/dfstepE' in rescheck['along_strip_data_extracted']);
    print('Run?',not doWeRunTheNotebook)
    if(not doWeRunTheNotebook):
        octstudies_to_run.append(octstudy);

print('~~~~~~~');
print('We will run the processing on {:} octstudies.'.format(len(octstudies_to_run)))
print([x.name for x in octstudies_to_run])

In [ ]:
# Prepare notebook to run
import papermill

#nbpath = r"C:\Users\SimonGhionea\OneDrive - Global Health Labs, Inc\ProjectsCloud\NAATOS\sgpyanalysisoct\sandbox_sg\nb_test_nbparams.ipynb";
#nbpath = r"C:\Users\SimonGhionea\OneDrive - Global Health Labs, Inc\ProjectsCloud\NAATOS\sgpyanalysisoct\sandbox_sg\octproc_20250429_process_a_longstrip.ipynb";
nbpath = r"C:\Users\SimonGhionea\OneDrive - Global Health Labs, Inc\ProjectsCloud\NAATOS\sgpyanalysisoct\sandbox_sg\octproc_20250507_process_E_longstripmetric.ipynb";

parameters = papermill.inspect_notebook(nbpath)
pp.pprint(parameters);

In [ ]:
# Call notebooks in parallel
import concurrent.futures

def run_notebook_on_an_octstudy(octstudy : naatos_oct_tools.thorlabs_oct_file_reading.OCT_Study_Folder):
    folder_temp_path = Path(r'D:\TEMP\OCTtmp');

    for nbpath in nbpaths:
        nbpath_out = folder_temp_path/(Path(nbpath).stem+'_OUT_{:s}.ipynb').format(octstudy.name)

    # set output path
    #nbpath_out = Path(nbpath).parent/(Path(nbpath).stem+'_OUT{:s}.ipynb').format(octstudy.name)
    nbpath_out = Path(r'C:\TEMP\OCTtmp')/(Path(nbpath).stem+'_OUT_{:s}.ipynb').format(octstudy.name)
    print(nbpath_out);

    # # execute a notebook
    papermill.execute_notebook(
        input_path=nbpath,
        output_path=nbpath_out,
        parameters=dict(codename = Path(nbpath).name,study_name=octstudy.name)
    )
    # print('start',octstudy.name);
    # time.sleep(1)
    # print('stop',octstudy.name)

# Using concurrent.futures to handle multiprocessing
def run_in_parallel(num_processes):
    # with concurrent.futures.ProcessPoolExecutor(max_workers=num_processes) as executor:
    #     futures = [executor.submit(run_notebook_on_an_octstudy, octstudy) for octstudy in octstudies_to_run]
    #     for future in concurrent.futures.as_completed(futures):
    #         print(future.result())  # You can handle results or exceptions here
    with concurrent.futures.ThreadPoolExecutor(max_workers=num_processes) as executor:
        futures = [executor.submit(run_notebook_on_an_octstudy, octstudy) for octstudy in octstudies_to_run]
        for future in concurrent.futures.as_completed(futures):
            print(future.result())

# Example usage
num_processes = 4;  # Number of parallel processes
run_in_parallel(num_processes);

# Processing Step 0 - Replace VTK scalars with scaled bytes

In [ ]:
#del vdvol;
#del scalars_rescaled_as_int

# Develop VTK Range Rescaling and integer

In [ ]:
def doVtkImageMinMaxScaling(vtkimagedata):
    # restrict range and re-scale, cast to integer (will reduce memory by 4x)
    oct_scalar_min = 30;
    oct_scalar_max = 60;

    import vtk

    # Create VTK Pipeline Connections
    # 1. Thresholding Hi
    alg_thresholder = vtk.vtkImageThreshold();
    alg_thresholder.SetInputData(vtkimagedata)
    alg_thresholder.ThresholdByUpper(oct_scalar_min);
    alg_thresholder.SetOutValue(oct_scalar_min);
    alg_thresholder.ReplaceInOff();
    alg_thresholder.ReplaceOutOn();

    # 2. Thresholding Lo
    alg_thresholder2 = vtk.vtkImageThreshold();
    alg_thresholder2.SetInputConnection(alg_thresholder.GetOutputPort());
    alg_thresholder2.ThresholdByLower(oct_scalar_max);
    alg_thresholder2.SetOutValue(oct_scalar_max);
    alg_thresholder2.ReplaceInOff();
    alg_thresholder2.ReplaceOutOn();

    # 3. Subtract Minimum Value
    alg_math1 = vtk.vtkImageMathematics();
    alg_math1.SetInputConnection(alg_thresholder2.GetOutputPort());
    alg_math1.SetConstantC(-oct_scalar_min);
    alg_math1.SetOperationToAddConstant();

    # 4. Rescale to 0 to 255
    alg_math2 = vtk.vtkImageMathematics();
    alg_math2.SetInputConnection(alg_math1.GetOutputPort());
    alg_math2.SetConstantK(255.0/oct_scalar_min);
    alg_math2.SetOperationToMultiplyByK();
    #cast to unit8_t byte
    #alg_math2.SetOutputS();

    # 5. Cast to Uint8
    alg_caster = vtk.vtkImageCast();
    alg_caster.SetInputConnection(alg_math2.GetOutputPort());
    alg_caster.SetOutputScalarTypeToUnsignedChar();


    # execute the vtk pipline, wrap with pyvista, and return
    alg_final = alg_caster;
    alg_final.Update();

    final = pv.wrap(alg_final.GetOutput())
    return final;
mergedvol_rescaled = doVtkImageMinMaxScaling(mergedvol);

In [ ]:
np.max(mergedvol.active_scalars)

In [ ]:
print(np.min(mergedvol_rescaled.active_scalars),np.max(mergedvol_rescaled.active_scalars))

In [ ]:
mergedvol_rescaled['OCTintensity']

In [ ]:
del mergedvol,mergedvol_rescaled,alg_thresholder

In [ ]:
del alg_final